FROM ubuntu:22.04
RUN apt-get update && \
    apt-get install -y clang build-essential && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY src/ .
RUN clang++ -std=c++17 -O2 -o app Clients_queue.cpp
CMD ["./app"]
